coords: "data/chignolin_ca_coords.npy"
forces: "data/chignolin_ca_deltaforces.npy"
embeddings: "data/chignolin_ca_embeddings.npy"
log_dir: train_light
num_epochs: 200
batch_size: 1024
lr: 0.0001
lr_patience: 4
lr_min: 1.e-06
lr_factor: 0.8
distributed_backend: dp
gpus: 4
num_nodes: 1
num_workers: 8
seed: 1
eval_interval: 1
save_interval: 1
progress: True
val_ratio: 0.05
test_ratio: 0.1
num_filters: 128
num_gaussians: 150
num_interactions: 3
max_z: 100
cutoff: 9