
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-12T20:56:37+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1f43c26ae380e6a81cb8fa4956a225801aca03f",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
