dataset: "Custom"
coord_files: "data/chignolin_ca_coords.npy"
force_files: "data2/chignolin_ca_deltaforces.npy"
embed_files: "data2/chignolin_ca_embeddings.npy"
# used to take the derivative of the prediction w.r.t coordinates,
# because data is force, not energy
derivative: true
log_dir: train_log
num_epochs: 200
batch_size: 1024
lr: 0.0001
lr_patience: 4
lr_min: 1.e-06
lr_factor: 0.8
ngpus: 2
num_nodes: 1
num_workers: 8
seed: 1
test_interval: 1
save_interval: 1
val_size: 0.05
test_size: 0.1
# embedding_dimension is num_filters in schnet
embedding_dimension: 128
rbf_type: "gauss"
num_rbf: 150
# num_layers is num_interactions in schnet
num_layers: 3
max_z: 100
# I guess cutoff_upper equals cutoff in the original train.yaml
cutoff_upper: 9