name: torchmd-cg
channels:
  - conda-forge
  - pytorch
  - nvidia
  - acellera
dependencies:
  - h5py
  - pyyaml
  - ipython
  - scikit-learn
  - scipy
  - moleculekit
  - seaborn
  - pandas
  - jupyter
  - matplotlib
  - parmed
  - tqdm
  - networkx
  - nnpops==0.2
  # conda does not contain torch, only pytorch
  - pytorch==1.11.0
  - pytorch-cuda==11.7
  - pytorch_cluster==1.5.9
  - pytorch_geometric==2.0.3
  - pytorch_scatter==2.0.8
  - pytorch_sparse==0.6.10
  - pytorch-lightning==1.6.3
  - torchmetrics==0.8.2
  # Dev tools
  - flake8
  - pytest
  - psutil